

spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false      

