

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_SCHEME}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_RESOURCE_SERVER}
    
elasticsearch:
  host: ${ELASTIC_HOST}
  api-key: ${ELASTIC_APIKEY}
  
google:
  firebase:
    api-key: ${FIREBASE_APIKEY}
